import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Book from '#models/book'
export default class BookSeeder extends BaseSeeder {
  async run() {
    await Book.createMany([
      {
        title: 'The Great Gatsby',
        description: 'A story of decadence and excess, exploring the American Dream in the Jazz Age',
        author: 'F. Scott Fitzgerald',
        genre: 'Fiction',
        year_publication: '1925',
        quantity: 10,
      },
      {
        title: 'To Kill a Mockingbird',
        description: 'A story of racial injustice and moral growth in the American South',
        author: 'Harper Lee',
        genre: 'Fiction',
        year_publication: '1960',
        quantity: 15,
      },
      {
        title: '1984',
        description: 'A dystopian novel about totalitarianism and surveillance',
        author: 'George Orwell',
        genre: 'Dystopian',
        year_publication: '1949',
        quantity: 20,
      },
      {
        title: 'Pride and Prejudice',
        description: 'A romantic novel about manners and matrimonial machinations',
        author: 'Jane Austen',
        genre: 'Romance',
        year_publication: '1813',
        quantity: 14,
      },
      {
        title: 'The Hobbit',
        description: 'A fantasy novel about the journey of Bilbo Baggins',
        author: 'J.R.R. Tolkien',
        genre: 'Fantasy',
        year_publication: '1937',
        quantity: 25,
      },
      {
        title: 'Fahrenheit 451',
        description: 'A dystopian novel about a future where books are banned and burned',
        author: 'Ray Bradbury',
        genre: 'Dystopian',
        year_publication: '1953',
        quantity: 22,
      },
      {
        title: 'Jane Eyre',
        description: 'A novel about the experiences of the titular character, including her growth to adulthood and love for Mr. Rochester',
        author: 'Charlotte Bronte',
        genre: 'Romance',
        year_publication: '1847',
        quantity: 11,
      },
      {
        title: 'Crime and Punishment',
        description: 'A psychological novel about the moral dilemmas of a young man who commits a murder',
        author: 'Fyodor Dostoevsky',
        genre: 'Psychological',
        year_publication: '1866',
        quantity: 7,
      },
      {
        title: 'The Odyssey',
        description: 'An epic poem about the adventures of Odysseus',
        author: 'Homer',
        genre: 'Epic',
        year_publication: '8th century BC',
        quantity: 9,
      },
      {
        title: 'The Divine Comedy',
        description: 'An epic poem about the journey through Hell, Purgatory, and Paradise',
        author: 'Dante Alighieri',
        genre: 'Epic',
        year_publication: '14th century',
        quantity: 4,
      },
      {
        title: 'Les Miserables',
        description: 'A historical novel about the struggles of several characters in 19th century France',
        author: 'Victor Hugo',
        genre: 'Historical',
        year_publication: '1862',
        quantity: 10,
      },
      {
        title: 'Anna Karenina',
        description: 'A novel about the tragic love affair between Anna Karenina and Count Vronsky',
        author: 'Leo Tolstoy',
        genre: 'Romance',
        year_publication: '1877',
        quantity: 8,
      },
      {
        title: 'The Count of Monte Cristo',
        description: 'An adventure novel about the story of Edmond Dantes and his quest for revenge',
        author: 'Alexandre Dumas',
        genre: 'Adventure',
        year_publication: '1844',
        quantity: 15,
      },
      {
        title: 'Wuthering Heights',
        description: 'A novel about the intense and destructive love between Catherine Earnshaw and Heathcliff',
        author: 'Emily Bronte',
        genre: 'Romance',
        year_publication: '1847',
        quantity: 12,
      },
      {
        title: 'Great Expectations',
        description: 'A novel about the growth and personal development of an orphan named Pip',
        author: 'Charles Dickens',
        genre: 'Fiction',
        year_publication: '1861',
        quantity: 14,
      },
      {
        title: 'The Picture of Dorian Gray',
        description: 'A philosophical novel about the moral corruption of Dorian Gray',
        author: 'Oscar Wilde',
        genre: 'Philosophical',
        year_publication: '1890',
        quantity: 11,
      },
      {
        title: 'Dracula',
        description: 'A horror novel about the vampire Count Dracula',
        author: 'Bram Stoker',
        genre: 'Horror',
        year_publication: '1897',
        quantity: 9,
      },
      {
        title: 'Frankenstein',
        description: 'A horror novel about the scientist Victor Frankenstein and his creation',
        author: 'Mary Shelley',
        genre: 'Horror',
        year_publication: '1818',
        quantity: 7,
      },
      {
        title: 'The Adventures of Huckleberry Finn',
        description: 'An adventure novel about the journey of Huck Finn and Jim along the Mississippi River',
        author: 'Mark Twain',
        genre: 'Adventure',
        year_publication: '1884',
        quantity: 10,
      },
      {
        title: 'Don Quixote',
        description: 'An adventure novel about the misadventures of Don Quixote and his squire Sancho Panza',
        author: 'Miguel de Cervantes',
        genre: 'Adventure',
        year_publication: '1605',
        quantity: 11,
      },
      {
        title: 'The Grapes of Wrath',
        description: 'A novel about the struggles of the Joad family during the Great Depression',
        author: 'John Steinbeck',
        genre: 'Fiction',
        year_publication: '1939',
        quantity: 7,
      },
      {
        title: 'Of Mice and Men',
        description: 'A novel about the friendship and dreams of two displaced ranch workers during the Great Depression',
        author: 'John Steinbeck',
        genre: 'Fiction',
        year_publication: '1937',
        quantity: 10,
      },
      {
        title: 'The Old Man and the Sea',
        description: 'A novel about the struggle between an old fisherman and a giant marlin',
        author: 'Ernest Hemingway',
        genre: 'Fiction',
        year_publication: '1952',
        quantity: 12,
      },
      {
        title: 'The War of the Worlds',
        description: 'A science fiction novel about an alien invasion of Earth',
        author: 'H.G. Wells',
        genre: 'Science Fiction',
        year_publication: '1898',
        quantity: 14,
      },
      {
        title: 'The Time Machine',
        description: 'A science fiction novel about a man who travels through time',
        author: 'H.G. Wells',
        genre: 'Science Fiction',
        year_publication: '1895',
        quantity: 6,
      }
    ])
  }
}