import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Book from '#models/book'
export default class BookSeeder extends BaseSeeder {
  async run() {
    await Book.createMany([
      {
        title: 'The Great Gatsby',
        author: 'F. Scott Fitzgerald',
        genre: 'Fiction',
        isbn: '9780743273565',
        quantity: 10,
      },
      {
        title: 'To Kill a Mockingbird',
        author: 'Harper Lee',
        genre: 'Fiction',
        isbn: '9780061120084',
        quantity: 15,
      },
      {
        title: '1984',
        author: 'George Orwell',
        genre: 'Dystopian',
        isbn: '9780451524935',
        quantity: 20,
      },
      {
        title: 'Pride and Prejudice',
        author: 'Jane Austen',
        genre: 'Romance',
        isbn: '9781503290563',
        quantity: 14,
      },
      {
        title: 'The Hobbit',
        author: 'J.R.R. Tolkien',
        genre: 'Fantasy',
        isbn: '9780547928227',
        quantity: 25,
      },
      {
        title: 'Fahrenheit 451',
        author: 'Ray Bradbury',
        genre: 'Dystopian',
        isbn: '9781451673319',
        quantity: 22,
      },
      {
        title: 'Jane Eyre',
        author: 'Charlotte Bronte',
        genre: 'Romance',
        isbn: '9780141441146',
        quantity: 11,
      },
      {
        title: 'Crime and Punishment',
        author: 'Fyodor Dostoevsky',
        genre: 'Psychological',
        isbn: '9780143058144',
        quantity: 7,
      },
      {
        title: 'The Odyssey',
        author: 'Homer',
        genre: 'Epic',
        isbn: '9780140268867',
        quantity: 9,
      },
      {
        title: 'The Divine Comedy',
        author: 'Dante Alighieri',
        genre: 'Epic',
        isbn: '9780142437223',
        quantity: 4,
      },
      {
        title: 'Les Miserables',
        author: 'Victor Hugo',
        genre: 'Historical',
        isbn: '9780451419439',
        quantity: 10,
      },
      {
        title: 'Anna Karenina',
        author: 'Leo Tolstoy',
        genre: 'Romance',
        isbn: '9780143035008',
        quantity: 8,
      },
      {
        title: 'The Count of Monte Cristo',
        author: 'Alexandre Dumas',
        genre: 'Adventure',
        isbn: '9780140449266',
        quantity: 15,
      },
      {
        title: 'Wuthering Heights',
        author: 'Emily Bronte',
        genre: 'Romance',
        isbn: '9780141439556',
        quantity: 12,
      },
      {
        title: 'Great Expectations',
        author: 'Charles Dickens',
        genre: 'Fiction',
        isbn: '9780141439563',
        quantity: 14,
      },
      {
        title: 'The Picture of Dorian Gray',
        author: 'Oscar Wilde',
        genre: 'Philosophical',
        isbn: '9780141439570',
        quantity: 11,
      },
      {
        title: 'Dracula',
        author: 'Bram Stoker',
        genre: 'Horror',
        isbn: '9780141439587',
        quantity: 9,
      },
      {
        title: 'Frankenstein',
        author: 'Mary Shelley',
        genre: 'Horror',
        isbn: '9780141439594',
        quantity: 7,
      },
      {
        title: 'The Adventures of Huckleberry Finn',
        author: 'Mark Twain',
        genre: 'Adventure',
        isbn: '9780141439600',
        quantity: 10,
      },
      {
        title: 'Don Quixote',
        author: 'Miguel de Cervantes',
        genre: 'Adventure',
        isbn: '9780141439655',
        quantity: 11,
      },
      {
        title: 'The Grapes of Wrath',
        author: 'John Steinbeck',
        genre: 'Fiction',
        isbn: '9780141439679',
        quantity: 7,
      },
      {
        title: 'Of Mice and Men',
        author: 'John Steinbeck',
        genre: 'Fiction',
        isbn: '9780141439686',
        quantity: 10,
      },
      {
        title: 'The Old Man and the Sea',
        author: 'Ernest Hemingway',
        genre: 'Fiction',
        isbn: '9780141439693',
        quantity: 12,
      },
      {
        title: 'The War of the Worlds',
        author: 'H.G. Wells',
        genre: 'Science Fiction',
        isbn: '9780141439808',
        quantity: 14,
      },
      {
        title: 'The Time Machine',
        author: 'H.G. Wells',
        genre: 'Science Fiction',
        isbn: '9780141439792',
        quantity: 6,
      }
    ])
  }
}